version: "3"
services:

#
# Instructions:
# 1: docker swarm init
# 2: docker stack deploy -c docker-compose.yml commerce
# 3: Browser http://localhost

  db2:
    image: commerce/ts-db:9.0.1.1
    hostname: auth_db
    privileged: true
    environment:
      - LICENSE=accept
      - TZ=Toronto/Canada
    ports:
      - 50000:50000
    healthcheck:
      test: exit 0

  mq:
    image: ibmcom/mq:latest
    hostname: auth_mq
    environment:
      - LICENSE=accept
      - TZ=Toronto/Canada
    ports:
      - 1414:1414
      - 9157:9157
      - 9443:9443

  webserver:
    image: commerce/ts-web:9.0.1.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
   
  store:
    image: commerce/crs-app:9.0.1.1
    hostname: auth_store
    environment:
      - LICENSE=accept
      - TZ=Toronto/Canada
    volumes:
      - /opt/logs/store:/opt/WebSphere/CommerceServer90/usr/servers/default/logs/container
    ports:
      - 8080:8080
      - 8443:8443
    healthcheck:
      test: curl -f http://localhost:8080/wcs/HealthCheck.jsp
      interval: 10s
      timeout: 180s
      retries: 100

networks:
  webnet:
